version: '3'
services:
  authentication:
    container_name: authentication
    build:
      context: ./authentication
    ports:
      - "5000:5000"
    volumes:
      - ./authentication:/app
    depends_on:
      - authentication_db

  authentication_db:
    container_name: authentication_db
    image: postgres:latest
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password

  catalog:
    container_name: catalog
    build:
      context: ./catalogue
    ports:
      - "5001:5001"
    volumes:
      - ./catalogue:/app
    depends_on:
      - catalog_db

  catalog_db:
    container_name: catalog_db
    image: postgres:latest
    environment:
      POSTGRES_DB: catalog_db
      POSTGRES_USER: catalog_user
      POSTGRES_PASSWORD: catalog_password

  cart:
    container_name: cart
    build:
      context: ./cart
    ports:
      - "5002:5002"
    volumes:
      - ./cart:/app
    depends_on:
      - cart_db

  cart_db:
    container_name: cart_db
    image: postgres:latest
    environment:
      POSTGRES_DB: cart_db
      POSTGRES_USER: cart_user
      POSTGRES_PASSWORD: cart_password

  notification:
    container_name: notification
    build:
      context: ./notification
    ports:
      - "5003:5003"
    volumes:
      - ./notification:/app
    depends_on:
      - kafka

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8
    ports:
      - "5672:5672"     # RabbitMQ default port
      - "15672:15672"   # RabbitMQ management console
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: <PASSWORD>
      RABBITMQ_DEFAULT_VHOST: "/"
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
    networks:
      - rabbitmq-network  

networks:
  rabbitmq-network:
    driver: bridge
  